In [3]:
import torch



In [4]:
randint = torch.randint(-100,100,(6,))

In [5]:
randint

tensor([-83,  56, -65,  -6,  90, -59])

In [6]:
tensor = torch.tensor([[0.1,1.2],[4.1,5.2],[1.1,2.2]])
tensor

tensor([[0.1000, 1.2000],
        [4.1000, 5.2000],
        [1.1000, 2.2000]])

In [7]:
zeroes = torch.zeros(2,3)
ones=torch.ones(2,3)
zeroes , ones

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [8]:
input = torch.empty(2,3)
input

tensor([[-6.6700e-24,  1.3957e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3,10,5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
logspace  = torch.logspace(-10,10,5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
torch.empty((2,3),dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.cat((torch.tensor([1,2,3,4]), torch.tensor([5])),dim=0) , torch.cat((torch.tensor([1,2,3,4]), torch.tensor([5])),dim=-1)

(tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5]))

In [15]:
torch.tril(torch.ones(3,3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [16]:
torch.triu(torch.ones(3,3))

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])

In [17]:
torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [18]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
tensor3=torch.tensor([7,8,9])
torch.stack([tensor1,tensor2,tensor3])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
import torch.nn.functional as F
import torch.nn as nn

In [20]:
tensor4 = torch.tensor([1.0,2.0,3.0])
linear = nn.Linear(3,3,bias=False)
linear

Linear(in_features=3, out_features=3, bias=False)

In [21]:

softmax_output = F.softmax(tensor4,dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])